networks:
  ask:
    driver: 'bridge'
services:
  ui:
    networks:
      - 'ask'
    image: 'ask-ui:latest'
    ports:
      - '8001:80'
    depends_on:
      - 'api'
  api:
    networks:
      - 'ask'
    image: 'ask-api:latest'
    ports:
      - '8080'
    volumes:
      - './secrets:/app/secrets'
    env_file:
      - './secrets/env_file.txt'
    depends_on:
      - 'postgres'
  postgres:
    networks:
      - 'ask'
    image: 'pgvector/pgvector:pg16'
    labels:
      - 'org.springframework.boot.service-connection=postgres:latest'
    environment:
      - 'POSTGRES_DB=angular'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=angular'
    ports:
      - '5432'
    volumes:
      - './setup/load-pgvector.sql:/docker-entrypoint-initdb.d/init.sql'
